#
# run with "rubocop" from this directory (no arguments)
# configuration documentation https://rubocop-sketchup.readthedocs.io/en/latest/
# this config is similar to https://rubocop-sketchup.readthedocs.io/en/latest/basic_usage/
# needs
# $ gem install rubocop-sketchup
# check the versions that were installed
# $ gem list --local | grep rubocop
# currently using versions:
# rubocop (1.75.6)
# rubocop-ast (1.44.1)
# rubocop-sketchup (1.5.0)
# 
# update all installed gems (may not be necessary)
# $ gem update `gem outdated | cut -d ' ' -f 1`
#
require: rubocop-sketchup

AllCops:
  Exclude:
    - 'build/**/*'
    - 'dist/**/*'
    - 'docs/**/*'
    - 'test/**/*'
    - 'tools/**/*'
  SketchUp:
    TargetSketchUpVersion: 2024
    SourcePath: src
  DisabledByDefault: true
  ExtraDetails: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.2

SketchupRequirements:
  Enabled: true

SketchupDeprecations:
  Enabled: true

SketchupPerformance:
  Enabled: true

SketchupSuggestions:
  Enabled: true

SketchupBugs:
  Enabled: true

SketchupSuggestions/Compatibility:
  Enabled: false

Security/Eval:
  Enabled: true
