#
# run with "rubocop" from this directory (no arguments)
# configuration documentation https://rubocop-sketchup.readthedocs.io/en/latest/
# this config is similar to https://rubocop-sketchup.readthedocs.io/en/latest/basic_usage/
# needs
# $ gem install rubocop-sketchup
# check the versions that were installed
# $ gem list --local | grep rubocop
# rubocop (1.75.6)
# rubocop-ast (1.44.1)
# rubocop-sketchup (1.5.0)
#
require: rubocop-sketchup

AllCops:
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2018
  Exclude:
    - build/*
    - test/*
  DisabledByDefault: true

SketchupDeprecations:
  Enabled: true

SketchupPerformance:
  Enabled: false

SketchupRequirements:
  Enabled: true

SketchupSuggestions:
  Enabled: false

SketchupBugs:
  Enabled: true
